In [2]:
import numpy as np
import pandas as pd
import sys

#PERFORM CALCULATIONS AND CREATE THE DATAFRAME

#Create the Dataframe
filename = 'PrOData.csv'
df = pd.read_csv(filename)

#Calculate Pro%
df['PrO%'] = df['PrO']/df['PrOO']

#Calculate the Average PrO%
tot_prop = df['PrO%'].sum()
tot_rows = len(df)
avg_prop = round(tot_prop/tot_rows, 3)

#Calculate the % of PrO that resulted in RBIs
df['RBI%'] = df['RBI']/df['PrO']

#Calculate the total strike out percentages
df['SO%'] = df['SO']/df['TOT_AB']

#Calculate the strike out percentage in PrO Opportunities
df['PrOSO%'] = df['PrOK']/df['PrOO']
    
def player_lookup(first, last):
    lookup_row = df.loc[(df['LAST_NAME_TX'] == last) & (df['FIRST_NAME_TX'] == first)]
    return lookup_row

df.head()

,LAST_NAME_TX,FIRST_NAME_TX,PrOO,PrO,PrOK,RBI,SO,TOT_AB,PrO%,RBI%,SO%,PrOSO%
0,Pence,Hunter,1794,372,474,35,508,2887,0.207358,0.094086,0.175961,0.264214
1,Young,Delmon,1386,222,288,39,376,2249,0.160173,0.175676,0.167185,0.207792
2,Gonzalez,Adrian,1330,345,315,38,448,2884,0.259398,0.110145,0.155340,0.236842
3,Young,Michael,1310,315,255,44,377,2928,0.240458,0.139683,0.128757,0.194656
4,Francoeur,Jeff,1224,198,318,31,387,2120,0.161765,0.156566,0.182547,0.259804

In [2]:
print('######## WELCOME TO THE 2010-2016 Pro% Calculator ########')

def get_input():

    print('Enter the first name of the player: ')
    first = input()
    print('Enter the last name of the player: ')
    last = input()
    
    if((first in df.values) and (last in df.values)):
        row = player_lookup(first, last)
    else:
        print('Player not contained in database, please enter another name')
        get_input()
        
    row_prop = row['PrO%'].to_string(index = False)
    prop_diff = round(abs(float(row_prop) - float(avg_prop)), 3)
    

    print(' ')
    print('Productive Out Statistics for {0} {1}: '.format(first, last))
    print(' ')

    print('PrOO: {0}'.format(round(row['PrOO'], 3).to_string(index = False)))
    print('PrO: {0}'.format(round(row['PrO'], 3).to_string(index = False)))
    print('PrO%: {0}'.format(round(row['PrO%'], 3).to_string(index = False)))
    print('PrO_RBI: {0}'.format(round(row['RBI'], 3).to_string(index = False)))
    print('PrO_RBI %: {0}'.format(round(row['RBI%'], 3).to_string(index = False)))
    print('Total SO %: {0}'.format(round(row['SO%'], 3).to_string(index = False)))
    print('PrO SO%: {0}'.format(round(row['PrOSO%'], 3).to_string(index = False)))

    print(' ')
    if(float(row_prop) < float(avg_prop)):
        print('{0} {1} is {2} below the league average for PrO%'.format(first, last, prop_diff))
    else:
        print('{0} {1} is {2} above the league average for PrO%'.format(first, last, prop_diff))
    print('The league average for PrO% is {0}'.format(avg_prop))
    
    print(' ')
    print('Would you like to look up another player\'s productive out stats? [y]/[n]')
    choice = input()
    if (choice == 'y' or choice == 'yes'):
        print (' ')
        get_input()
    else:
        print(' ')
        print('Thank you!')
        quit()
    

get_input()

#print('PrOO: {0},'.format(row['PrOO'])

######## WELCOME TO THE 2010-2016 Pro% Calculator ########
Enter the first name of the player:
Charlie
Enter the last name of the player:
Blackmon

Productive Out Statistics for Charlie Blackmon:

PrOO: 105
PrO: 18
PrO%: 0.171
PrO_RBI: 2
PrO_RBI %: 0.111
Total SO %: 0.151
PrO SO%: 0.114

Charlie Blackmon is 0.072 below the league average for PrO%
The league average for PrO% is 0.243

Would you like to look up another player's productive out stats? [y]/[n]
n

Thank you!

In [3]:
df.corr(method = 'pearson')**2

,PrOO,PrO,PrOK,RBI,SO,TOT_AB,PrO%,RBI%,SO%,PrOSO%
PrOO,1.000000,0.883850,0.829084,0.834295,0.782774,0.912848,0.020033,0.026833,0.139704,0.014887
PrO,0.883850,1.000000,0.614966,0.745027,0.628013,0.849641,0.000105,0.041186,0.157107,0.041414
PrOK,0.829084,0.614966,1.000000,0.612797,0.879574,0.731868,0.042049,0.022280,0.039927,0.008421
RBI,0.834295,0.745027,0.612797,1.000000,0.671840,0.868981,0.025802,0.002512,0.199591,0.037385
SO,0.782774,0.628013,0.879574,0.671840,1.000000,0.835563,0.035192,0.017111,0.057819,0.000615
TOT_AB,0.912848,0.849641,0.731868,0.868981,0.835563,1.000000,0.020954,0.017393,0.194204,0.023502
PrO%,0.020033,0.000105,0.042049,0.025802,0.035192,0.020954,1.000000,0.135079,0.007250,0.130024
RBI%,0.026833,0.041186,0.022280,0.002512,0.017111,0.017393,0.135079,1.000000,0.012263,0.001632
SO%,0.139704,0.157107,0.039927,0.199591,0.057819,0.194204,0.007250,0.012263,1.000000,0.317769
PrOSO%,0.014887,0.041414,0.008421,0.037385,0.000615,0.023502,0.130024,0.001632,0.317769,1.000000

In [4]:
df.corr(method = 'pearson')

,PrOO,PrO,PrOK,RBI,SO,TOT_AB,PrOPercentage,RBI%,SO%,PrOSO%
PrOO,1.000000,0.940133,0.910540,0.913398,0.884745,0.955431,-0.141540,-0.163808,-0.373770,-0.122013
PrO,0.940133,1.000000,0.784198,0.863150,0.792473,0.921760,0.010259,-0.202943,-0.396367,-0.203504
PrOK,0.910540,0.784198,1.000000,0.782813,0.937856,0.855493,-0.205059,-0.149265,-0.199817,0.091767
RBI,0.913398,0.863150,0.782813,1.000000,0.819658,0.932191,-0.160629,-0.050120,-0.446756,-0.193351
SO,0.884745,0.792473,0.937856,0.819658,1.000000,0.914092,-0.187596,-0.130809,-0.240455,0.024797
TOT_AB,0.955431,0.921760,0.855493,0.932191,0.914092,1.000000,-0.144756,-0.131882,-0.440686,-0.153304
PrOPercentage,-0.141540,0.010259,-0.205059,-0.160629,-0.187596,-0.144756,1.000000,-0.367531,0.085149,-0.360588
RBI%,-0.163808,-0.202943,-0.149265,-0.050120,-0.130809,-0.131882,-0.367531,1.000000,-0.110739,-0.040402
SO%,-0.373770,-0.396367,-0.199817,-0.446756,-0.240455,-0.440686,0.085149,-0.110739,1.000000,0.563710
PrOSO%,-0.122013,-0.203504,0.091767,-0.193351,0.024797,-0.153304,-0.360588,-0.040402,0.563710,1.000000