In [2]:
import numpy as np
import pandas as pd
import sys

#PERFORM CALCULATIONS AND CREATE THE DATAFRAME

#Create the Dataframe
filename = 'PrOData.csv'
df = pd.read_csv(filename)

#Calculate Pro%
df['PrOPercentage'] = df['PrO']/df['PrOO']

#Calculate the Average PrO%
tot_prop = df['PrOPercentage'].sum()
tot_rows = len(df)
avg_prop = tot_prop/tot_rows

#Calculate the % of PrO that resulted in RBIs
df['RBI%'] = df['RBI']/df['PrO']
    
def player_lookup(first, last):
    lookup_row = df.loc[(df['LAST_NAME_TX'] == last) & (df['FIRST_NAME_TX'] == first)]
    return lookup_row

df.head()

  LAST_NAME_TX FIRST_NAME_TX  PrOO  PrO  RBI  PrOPercentage      RBI%
0        Pence        Hunter  1794  372   35       0.207358  0.094086
1        Young        Delmon  1386  222   39       0.160173  0.175676
2     Gonzalez        Adrian  1330  345   38       0.259398  0.110145
3        Young       Michael  1310  315   44       0.240458  0.139683
4    Francoeur          Jeff  1224  198   31       0.161765  0.156566

In [ ]:
print('######## WELCOME TO THE 2010-2016 Pro% Calculator ########')

def get_input():

    print('Enter the first name of the player: ')
    first = input()
    print('Enter the last name of the player: ')
    last = input()
    
    if((first in df.values) and (last in df.values)):
        row = player_lookup(first, last)
    else:
        print('Player not contained in database, please enter another name')
        get_input()
        
    row_prop = row['PrOPercentage'].to_string(index = False)
    prop_diff = abs(float(row_prop) - float(avg_prop))

    print(' ')
    print('Productive Out Statistics for {0} {1}: '.format(first, last))
    print(' ')

    print('PrOO: {0}'.format(row['PrOO'].to_string(index = False)))
    print('PrO: {0}'.format(row['PrO'].to_string(index = False)))
    print('PrO%: {0}'.format(row['PrOPercentage'].to_string(index = False)))
    print('PrO_RBI: {0}'.format(row['RBI'].to_string(index = False)))
    print('PrO_RBI %: {0}'.format(row['RBI%'].to_string(index = False)))

    print(' ')
    if(float(row_prop) < float(avg_prop)):
        print('{0} {1} is {2} below the league average for PrO%'.format(first, last, prop_diff))
    else:
        print('{0} {1} is {2} above the league average for PrO%'.format(first, last, prop_diff))
    print('The league average for PrO% is {0}'.format(avg_prop))
    
    print(' ')
    print('Would you like to look up another player\'s productive out stats? [y]/[n]')
    choice = input()
    if (choice == 'y' or choice == 'yes'):
        print (' ')
        get_input()
    else:
        print(' ')
        print('Thank you!')
        quit()
    

get_input()

#print('PrOO: {0},'.format(row['PrOO'])

In [3]:
df.corr(method = 'pearson')**2

                   PrOO       PrO       RBI  PrOPercentage      RBI%
PrOO           1.000000  0.883837  0.834292       0.020742  0.026616
PrO            0.883837  1.000000  0.745005       0.000039  0.040925
RBI            0.834292  0.745005  1.000000       0.026571  0.002449
PrOPercentage  0.020742  0.000039  0.026571       1.000000  0.132316
RBI%           0.026616  0.040925  0.002449       0.132316  1.000000